on: [push, pull_request]

defaults:
  run:
    shell: bash

# TODO: make pytest work without editable installs

jobs:

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install $(grep -E '^(black|flake8|mypy)' requirements.txt)
      - run: flake8 .
      - run: black . --check
      # - run: mypy --ignore-missing-imports .

  docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install $(grep ^pipe2codeblock requirements.txt)
      - run: pip install -e .
      - name: Check docs are up to date
        run: |
          make readme
          git diff --exit-code

  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: pytest -v

  deploy:
    runs-on: ubuntu-18.04
    needs: [lint, docs, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install build
      - run: python -m build --sdist --wheel --outdir dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
